############################################################
# Dockerfile to prepare variables
############################################################

FROM ubuntu:latest

CMD cd /app && \
prepare-vars/prepare-vars.sh && \
echo "vars configured" && \
exit
